Disable log decorating
The default newrelic.js comes with this enabled, but it mucks up
cloudwatch logs. I see other apps have this set to `false` so lets do it
here as well.

Tried to run locally before (note the NR-LINKING in the logs):
```
$ ENV=qa LOCAL=true
NEW_RELIC_LICENSE_KEY=4fc5a471d9f53dda9c14f60e9ba2085c7364NRAL npm start

> discovery-api@1.1.4 start
> ./start-server.sh

info: Load-config: Loaded config/qa.env for ENV 'qa' NR-LINKING||MA-CDOAD-091123|||Discovery%20API%20(local)|
(node:75314) Warning: NodeVersionSupportWarning: The AWS SDK for JavaScript (v3)
versions published after the first week of January 2027
will require node >=22. You are running node v20.20.2.

To continue receiving updates to AWS services, bug fixes,
and security updates please upgrade to node >=22.

More information can be found at: https://a.co/c895JFp
(Use `node --trace-warnings ...` to show where the warning was created)
error: Load-config: Failed to decrypt ENCRYPTED_ELASTICSEARCH_URI: CredentialsProviderError: Could not load credentials from any providers NR-LINKING|MTIxMzM0fEFQTXxBUFBMSUNBVElPTnwxNDUyNDI1NjIw|MA-CDOAD-091123|||Discovery%20API%20(local)|
error: Load-config: Failed to decrypt ENCRYPTED_ELASTICSEARCH_API_KEY: CredentialsProviderError: Could not load credentials from any providers NR-LINKING|MTIxMzM0fEFQTXxBUFBMSUNBVElPTnwxNDUyNDI1NjIw|MA-CDOAD-091123|||Discovery%20API%20(local)|
error: Load-config: Failed to decrypt ENCRYPTED_SCSB_URL: CredentialsProviderError: Could not load credentials from any providers NR-LINKING|MTIxMzM0fEFQTXxBUFBMSUNBVElPTnwxNDUyNDI1NjIw|MA-CDOAD-091123|||Discovery%20API%20(local)|
error: Load-config: Failed to decrypt ENCRYPTED_SCSB_API_KEY: CredentialsProviderError: Could not load credentials from any providers NR-LINKING|MTIxMzM0fEFQTXxBUFBMSUNBVElPTnwxNDUyNDI1NjIw|MA-CDOAD-091123|||Discovery%20API%20(local)|
error: Load-config: Failed to decrypt ENCRYPTED_NYPL_OAUTH_ID: CredentialsProviderError: Could not load credentials from any providers NR-LINKING|MTIxMzM0fEFQTXxBUFBMSUNBVElPTnwxNDUyNDI1NjIw|MA-CDOAD-091123|||Discovery%20API%20(local)|
error: Load-config: Failed to decrypt ENCRYPTED_NYPL_OAUTH_SECRET: CredentialsProviderError: Could not load credentials from any providers NR-LINKING|MTIxMzM0fEFQTXxBUFBMSUNBVElPTnwxNDUyNDI1NjIw|MA-CDOAD-091123|||Discovery%20API%20(local)|
```

After (without):
```
$ ENV=qa LOCAL=true NEW_RELIC_LICENSE_KEY=4fc5a471d9f53dda9c14f60e9ba2085c7364NRAL npm start

> discovery-api@1.1.4 start
> ./start-server.sh

info: Load-config: Loaded config/qa.env for ENV 'qa'
(node:75542) Warning: NodeVersionSupportWarning: The AWS SDK for JavaScript (v3)
versions published after the first week of January 2027
will require node >=22. You are running node v20.20.2.

To continue receiving updates to AWS services, bug fixes,
and security updates please upgrade to node >=22.

More information can be found at: https://a.co/c895JFp
(Use `node --trace-warnings ...` to show where the warning was created)
error: Load-config: Failed to decrypt ENCRYPTED_ELASTICSEARCH_URI: CredentialsProviderError: Could not load credentials from any providers
error: Load-config: Failed to decrypt ENCRYPTED_ELASTICSEARCH_API_KEY: CredentialsProviderError: Could not load credentials from any providers
error: Load-config: Failed to decrypt ENCRYPTED_SCSB_URL: CredentialsProviderError: Could not load credentials from any providers
error: Load-config: Failed to decrypt ENCRYPTED_SCSB_API_KEY: CredentialsProviderError: Could not load credentials from any providers
error: Load-config: Failed to decrypt ENCRYPTED_NYPL_OAUTH_ID: CredentialsProviderError: Could not load credentials from any providers
error: Load-config: Failed to decrypt ENCRYPTED_NYPL_OAUTH_SECRET: CredentialsProviderError: Could not load credentials from any providers
```